Add linux role, configure graylog automatically, add logging volume
RIT-GCI/code-red pull request #20
Opened 2023-11-12 18:54 UTC by gidoBOSSftw5731

2023-11-12 18:57 UTC, gidoBOSSftw5731 commented
Completes #6, all linux hosts automatically are configured to send logs to graylog. Windows is still unconfigured. A volume is also used to transitioning to persistent logging as easy as creating the volume outside of terraform and adding the ID as a variable.

2023-11-14 13:16 UTC, ashim-mahara requested changes
The installgraylog volumE errors should be addressed before the merge.

2023-11-14 13:16 UTC, ashim-mahara commented on terraform/ansible/playbooks/installgraylog.yml
> +    - name: run curl command to add syslog listener
Is there any other way to do this while configuring the server? Like any flags or options in the roles?

2023-11-14 13:19 UTC, gidoBOSSftw5731 commented on terraform/ansible/playbooks/installgraylog.yml
> +    - name: create volume for graylog
Error fixed

2023-11-14 13:21 UTC, gidoBOSSftw5731 commented on terraform/ansible/playbooks/installgraylog.yml
> +    - name: run curl command to add syslog listener
Graylog doesn't listen on 514 because it doesn't run as root. You can do some special capabilities on the binary but that all the official documentation just says to run iptables. You need to listen for "output" in order for logs from the graylog host to get redirected because the other rule doesn't apply to locally-originated packets.

2023-11-14 13:33 UTC, ashim-mahara approved these changes

2023-11-14 13:33 UTC, merged