Feature/configure sysmon
RIT-GCI/code-red pull request #31
Opened 2023-12-22 17:52 UTC by ashim-mahara

Completes the Sysmon + Winlogbeat Integration to Graylog Feature

2024-01-09 19:07 UTC, gidoBOSSftw5731 requested changes
Overall good, mostly just a few small checks to do

2024-01-09 19:07 UTC, gidoBOSSftw5731 commented on terraform/ansible/playbooks/set_dns_servers.yml
Why are we using network manager rather than just writing to /etc/resolv.conf and/or dhcp? We don't use network manager anyway and I don't think it'll override ifupdown...

2024-01-09 19:07 UTC, gidoBOSSftw5731 commented on terraform/elan-instances.tf
> +		EOF
Move this powershell stuff to a separate template file

2024-01-09 19:07 UTC, gidoBOSSftw5731 commented on terraform/elan-instances.tf
> +  user_data = <<EOF
also move this powershell to another file

2024-01-09 19:13 UTC, ashim-mahara commented on terraform/ansible/playbooks/set_dns_servers.yml
I had problems with that so I've left these here. I haven't tested if they're working or not since I was only working with the Windows instances for the DNS. Mostly because they wouldn't pickup the DNS from resolv.conf. I could try again to see if it was because the DNS server broke in one of the commits.

2024-01-09 19:17 UTC, ashim-mahara commented on terraform/ansible/bootstrap/bootstrapansible.sh.tftpl
> -%{ for variable_file in variable_files }
No, I moved everything to their respective roles.

2024-01-09 19:42 UTC, ashim-mahara commented on terraform/ansible/bootstrap/bootstrapansible.sh.tftpl
> -%{ for variable_file in variable_files }
But in hindsight, I might move everything to a single variable file, because some of those roles do contain overlapping variables.

2024-01-09 21:12 UTC, ashim-mahara commented on terraform/ansible/playbooks/set_dns_servers.yml
Done

2024-01-09 21:16 UTC, gidoBOSSftw5731 commented
Installing the resolvconf package is probably not what you actually want, unless you actually configure it in /etc/resolvconf.d 

Resolv.conf exists without the package, usually I just make it an immutable file and call it a day

2024-01-09 22:25 UTC, ashim-mahara commented
> Installing the resolvconf package is probably not what you actually want, unless you actually configure it in /etc/resolvconf.d
> 
> Resolv.conf exists without the package, usually I just make it an immutable file and call it a day

done

2024-01-10 13:24 UTC, ashim-mahara commented
Merging since all of the requested changes were done.

2024-01-10 13:24 UTC, merged

2024-01-10 13:43 UTC, ashim-mahara commented
Merged to develop using cmd git.